"use client";

import { useEffect, useMemo, useState } from "react";

const API = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8080";
const PAGE_SIZE = 20;

type Pricing = { input: string | null; output: string | null; cache_read: string | null; currency: string; observed_at: string };
type ModelItem = { id:string; slug:string; name:string; company:{slug:string;name:string}; context_window:number|null; capabilities:{input_modalities?:string[];output_modalities?:string[]}; pricing:Pricing|null };
type BenchmarkScore = { benchmark:string;benchmark_slug:string;rank:number;score:number;published_at:string;source_url:string };
type SourceInfo = { name:string;url:string;reliability:string;source_class:string|null };
type ModelDetail = ModelItem & { description:string|null; tokenizer:string|null; created:number|null; sources:SourceInfo[]; price_history:Pricing[];benchmarks:BenchmarkScore[] };
type Stats = { companies:number;models:number;snapshots:number;price_observations:number;change_events:number };
type EventItem = { id:string;event_type:string;entity_id:string;title:string;old_value:Record<string,unknown>|null;new_value:Record<string,unknown>|null;change_percentage:string|null;importance:string;detected_at:string };
type LeaderboardItem = { model_name:string;organization:string;license:string;rating:number;rating_lower:number|null;rating_upper:number|null;vote_count:number|null;rank:number;category:string;leaderboard_publish_date:string;details:Record<string,unknown> };
type Leaderboard = { source:{name:string;url:string;benchmark:string};category:string;published_at:string|null;items:LeaderboardItem[] };
type SourceCatalogItem = {slug:string;name:string;url:string;category:string;source_class:string;collection_method:string;reliability:string;is_active:boolean;status:string|null;last_success_at:string|null};
type ResearchItem = {id:string;title:string;authors:string[];url:string;published_at:string|null;categories:string[]};
type TechnologyItem = {slug:string;name:string;category:string;strength:string;last_seen_at:string;evidence:Record<string,unknown>};
type NoticeItem = {id:string;title:string;body:string;importance:string;status:string;created_at:string;source_url?:string|null};
const emptyStats:Stats={companies:0,models:0,snapshots:0,price_observations:0,change_events:0};

function money(value:string|null|undefined){if(value==null)return "—";return `$${Number(value).toLocaleString("tr-TR",{maximumFractionDigits:4})}`}
function compact(value:number){return new Intl.NumberFormat("tr-TR",{notation:"compact"}).format(value)}
function trModality(tag:string){
  const map:Record<string,string>={text:"metin",image:"gorsel",audio:"ses",video:"video"};
  return map[tag.toLowerCase()]??tag;
}
function canOpenSourceUrl(url:string|null|undefined){
  if(!url)return false;
  const value=url.toLowerCase();
  if(!value.startsWith("http://")&&!value.startsWith("https://"))return false;
  if(value.includes("datasets-server.huggingface.co/rows"))return false;
  if(value.includes("/api/"))return false;
  if(value.includes("/api/v1/models"))return false;
  if(value.endsWith(".json")||value.endsWith(".jsonl")||value.endsWith(".csv"))return false;
  return true;
}
const eventMeta:Record<string,{label:string;icon:string;className:string}>={
  "model.released":{label:"Yeni model",icon:"✦",className:"release"},
  "leaderboard.changed":{label:"Benchmark hareketi",icon:"↗",className:"benchmark"},
  "benchmark.updated":{label:"Benchmark güncellendi",icon:"◎",className:"benchmark"},
  "context.changed":{label:"Teknoloji güncellemesi",icon:"↔",className:"technology"},
  "capability.changed":{label:"Yeni yetenek",icon:"+",className:"technology"},
  "github.release_published":{label:"GitHub sürümü",icon:"⌥",className:"technology"},
  "huggingface.updated":{label:"Hugging Face",icon:"◇",className:"technology"},
  "weights.released":{label:"Açık ağırlık",icon:"◇",className:"technology"},
  "license.changed":{label:"Lisans",icon:"§",className:"technology"},
  "company.announcement":{label:"Şirket duyurusu",icon:"!",className:"research"},
  "technology.detected":{label:"Teknoloji sinyali",icon:"⚡",className:"technology"},
  "research.published":{label:"Yeni araştırma",icon:"◌",className:"research"},
  "price.changed":{label:"Fiyat hareketi",icon:"$",className:"price"},
};
function eventInfo(type:string){return eventMeta[type]??{label:type.replaceAll("."," "),icon:"•",className:"other"}}
function cleanEventTitle(event:EventItem){return event.title.replace(" discovered"," yayınlandı").replace(": context_window changed"," — context penceresi değişti").replace(/: (input|output|cache_read)_per_1m_tokens changed/," — token fiyatı değişti").replace(": Arena rank changed"," — sıralaması değişti")}
function eventDetail(event:EventItem){
  if(event.event_type==="model.released"){const value=event.new_value??{};const context=Number(value.context_window);const modalities=[...((value.input_modalities as string[])??[]),...((value.output_modalities as string[])??[])];return [context?`${context.toLocaleString("tr-TR")} token context`:null,modalities.length?Array.from(new Set(modalities)).join(" + "):null].filter(Boolean).join(" • ")||"Yeni model kataloğa eklendi"}
  if(event.event_type==="price.changed")return event.change_percentage?`Fiyat ${Number(event.change_percentage)>0?"yükseldi":"düştü"}: %${Math.abs(Number(event.change_percentage)).toLocaleString("tr-TR",{maximumFractionDigits:1})}`:"Yeni fiyat bilgisi kaydedildi";
  if(event.event_type==="context.changed"){const before=Object.values(event.old_value??{})[0];const after=Object.values(event.new_value??{})[0];return `${Number(before).toLocaleString("tr-TR")} → ${Number(after).toLocaleString("tr-TR")} token`}
  if(event.event_type==="leaderboard.changed"){const before=Object.values(event.old_value??{})[0];const after=Object.values(event.new_value??{})[0];return `Sıra #${before} → #${after}`}
  return "Kaynak tarafından doğrulanan yeni gelişme";
}

export default function Home(){
  const [stats,setStats]=useState(emptyStats);const [models,setModels]=useState<ModelItem[]>([]);const [events,setEvents]=useState<EventItem[]>([]);const [arena,setArena]=useState<Leaderboard|null>(null);const [swebench,setSwebench]=useState<Leaderboard|null>(null);const [swebenchLive,setSwebenchLive]=useState<Leaderboard|null>(null);const [tauBench,setTauBench]=useState<Leaderboard|null>(null);const [aaIntelligence,setAaIntelligence]=useState<Leaderboard|null>(null);const [aaCoding,setAaCoding]=useState<Leaderboard|null>(null);const [aaAgentic,setAaAgentic]=useState<Leaderboard|null>(null);const [livebench,setLivebench]=useState<Leaderboard|null>(null);const [mmluPro,setMmluPro]=useState<Leaderboard|null>(null);const [livecodebench,setLivecodebench]=useState<Leaderboard|null>(null);const [leaderboardView,setLeaderboardView]=useState<"general"|"coding"|"swe-live"|"tau-bench"|"intelligence"|"aa-coding"|"agentic"|"livebench"|"mmlu-pro"|"livecodebench">("general");
  const [query,setQuery]=useState("");const [company,setCompany]=useState("all");const [page,setPage]=useState(1);const [loading,setLoading]=useState(true);const [error,setError]=useState(false);
  const [selected,setSelected]=useState<ModelItem[]>([]);const [detail,setDetail]=useState<ModelDetail|null>(null);const [detailLoading,setDetailLoading]=useState(false);
  const [sourceCatalog,setSourceCatalog]=useState<SourceCatalogItem[]>([]);
  const [research,setResearch]=useState<ResearchItem[]>([]);
  const [technology,setTechnology]=useState<TechnologyItem[]>([]);
  const [notices,setNotices]=useState<NoticeItem[]>([]);
  const [catalogOpen,setCatalogOpen]=useState(false);
  const [livebenchCategory,setLivebenchCategory]=useState("overall");const [mmluCategory,setMmluCategory]=useState("overall");
  const [sweLiveCategory,setSweLiveCategory]=useState("lite");const [tauCategory,setTauCategory]=useState("airline");
  useEffect(()=>{const optional=(url:string)=>fetch(url).then(r=>r.ok?r.json():null);Promise.all([fetch(`${API}/api/v1/stats`).then(r=>r.json()),fetch(`${API}/api/v1/models?limit=500`).then(r=>r.json()),fetch(`${API}/api/v1/events?limit=120`).then(r=>r.json()),fetch(`${API}/api/v1/leaderboards/arena?limit=20`).then(r=>r.json()),fetch(`${API}/api/v1/leaderboards/swe-bench?limit=20`).then(r=>r.json()),optional(`${API}/api/v1/leaderboards/artificial-analysis/intelligence?limit=20`),optional(`${API}/api/v1/leaderboards/artificial-analysis/coding?limit=20`),optional(`${API}/api/v1/leaderboards/artificial-analysis/agentic?limit=20`),optional(`${API}/api/v1/leaderboards/livebench?limit=20`),optional(`${API}/api/v1/leaderboards/mmlu-pro?limit=20`),optional(`${API}/api/v1/leaderboards/livecodebench?limit=20`)]).then(([s,m,e,a,sw,aai,aac,aaa,lb,mp,lcb])=>{setStats(s);setModels(m.items);setEvents(e.items);setArena(a);setSwebench(sw);setAaIntelligence(aai);setAaCoding(aac);setAaAgentic(aaa);setLivebench(lb);setMmluPro(mp);setLivecodebench(lcb)}).catch(()=>setError(true)).finally(()=>setLoading(false))},[]);
  useEffect(()=>{fetch(`${API}/api/v1/catalog/sources`).then(r=>r.ok?r.json():null).then(data=>setSourceCatalog(data?.items??[])).catch(()=>{});fetch(`${API}/api/v1/research?limit=8`).then(r=>r.ok?r.json():null).then(data=>setResearch(data?.items??[])).catch(()=>{});fetch(`${API}/api/v1/technology`).then(r=>r.ok?r.json():null).then(data=>setTechnology(data?.items??[])).catch(()=>{});fetch(`${API}/api/v1/notifications?limit=8`).then(r=>r.ok?r.json():null).then(data=>setNotices(data?.items??[])).catch(()=>{})},[]);
  useEffect(()=>{const stream=new EventSource(`${API}/api/v1/stream/events`);stream.addEventListener("change",ev=>{try{const incoming=JSON.parse(ev.data) as Partial<EventItem> & {id:string;event_type:string;title:string;importance:string;detected_at:string;source_url?:string|null};const item:EventItem={id:incoming.id,event_type:incoming.event_type,entity_id:incoming.entity_id??"",title:incoming.title,old_value:incoming.old_value??null,new_value:incoming.new_value??null,change_percentage:incoming.change_percentage??null,importance:incoming.importance,detected_at:incoming.detected_at};setEvents(current=>current.some(event=>event.id===item.id)?current:[item,...current].slice(0,120));setNotices(current=>[{id:item.id,title:item.title,body:item.event_type,importance:item.importance,status:"unread",created_at:item.detected_at,source_url:incoming.source_url??null},...current].slice(0,8))}catch{return}});return()=>stream.close()},[]);
  useEffect(()=>{const refreshAcademic=()=>Promise.all([fetch(`${API}/api/v1/leaderboards/livebench?category=${livebenchCategory}&limit=20`).then(r=>r.ok?r.json():null),fetch(`${API}/api/v1/leaderboards/mmlu-pro?category=${mmluCategory}&limit=20`).then(r=>r.ok?r.json():null)]).then(([lb,mp])=>{if(lb)setLivebench(lb);if(mp)setMmluPro(mp)}).catch(()=>{});const timer=window.setInterval(refreshAcademic,30000);const onVisible=()=>{if(document.visibilityState==="visible")void refreshAcademic()};document.addEventListener("visibilitychange",onVisible);return()=>{window.clearInterval(timer);document.removeEventListener("visibilitychange",onVisible)}},[livebenchCategory,mmluCategory]);
  useEffect(()=>{fetch(`${API}/api/v1/leaderboards/livebench?category=${livebenchCategory}&limit=20`).then(r=>r.ok?r.json():null).then(data=>{if(data)setLivebench(data)}).catch(()=>{})},[livebenchCategory]);
  useEffect(()=>{fetch(`${API}/api/v1/leaderboards/mmlu-pro?category=${mmluCategory}&limit=20`).then(r=>r.ok?r.json():null).then(data=>{if(data)setMmluPro(data)}).catch(()=>{})},[mmluCategory]);
  useEffect(()=>{fetch(`${API}/api/v1/leaderboards/swe-bench-live?category=${sweLiveCategory}&limit=20`).then(r=>r.ok?r.json():null).then(data=>{if(data)setSwebenchLive(data)}).catch(()=>{})},[sweLiveCategory]);
  useEffect(()=>{fetch(`${API}/api/v1/leaderboards/tau-bench?category=${tauCategory}&limit=20`).then(r=>r.ok?r.json():null).then(data=>{if(data)setTauBench(data)}).catch(()=>{})},[tauCategory]);
  const companies=useMemo(()=>Array.from(new Map(models.map(m=>[m.company.slug,m.company])).values()).sort((a,b)=>a.name.localeCompare(b.name)),[models]);
  const filtered=useMemo(()=>{const q=query.trim().toLocaleLowerCase("tr-TR");return models.filter(m=>(company==="all"||m.company.slug===company)&&(!q||`${m.name} ${m.company.name} ${m.slug}`.toLocaleLowerCase("tr-TR").includes(q)))},[models,query,company]);
  const visibleEvents=useMemo(()=>{const quotas:Record<string,number>={"model.released":5,"leaderboard.changed":3,"benchmark.updated":3,"context.changed":2,"capability.changed":2,"weights.released":2,"research.published":2,"price.changed":3};const counts:Record<string,number>={};const seenPriceModels=new Set<string>();return events.filter(event=>{if(event.event_type==="price.changed"){if(seenPriceModels.has(event.entity_id))return false;seenPriceModels.add(event.entity_id)}const max=quotas[event.event_type]??1;if((counts[event.event_type]??0)>=max)return false;counts[event.event_type]=(counts[event.event_type]??0)+1;return true}).slice(0,12)},[events]);
  const pages=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE));const visible=filtered.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE);
  function toggle(model:ModelItem){setSelected(current=>current.some(m=>m.id===model.id)?current.filter(m=>m.id!==model.id):current.length<3?[...current,model]:current)}
  async function openDetail(model:ModelItem){setDetailLoading(true);setDetail(null);try{const response=await fetch(`${API}/api/v1/models/${model.id}`);if(!response.ok)throw new Error("Model ayrıntıları alınamadı");setDetail(await response.json())}catch{setError(true)}finally{setDetailLoading(false)}}
  return <main id="top">
    <header className="topbar"><a className="brand" href="#top"><span className="brand-mark">LR</span><span>LLM RADAR</span></a><nav><a className="active" href="#overview">Genel Bakış</a><a href="#models">Modeller</a><a href="#compare">Karşılaştır</a><a href="#events">Gelişmeler</a><a href="#research">Araştırma</a><a href="#radar">Radar</a><a href="#sources">Kaynaklar</a></nav><div className="live-pill"><span/> CANLI</div></header>
    <section className="hero" id="overview"><div><p className="eyebrow">LLM INTELLIGENCE PLATFORM</p><h1>Yapay zekâ dünyasının<br/><em>nabzını tut.</em></h1><p className="hero-copy">Modelleri, fiyatları ve teknoloji değişimlerini tek merkezden, kaynaklarıyla birlikte takip et.</p></div><div className="radar"><span className="orbit orbit-one"/><span className="orbit orbit-two"/><span className="orbit orbit-three"/><span className="sweep"/><span className="dot dot-one"/><span className="dot dot-two"/><span className="dot dot-three"/><b>{stats.models||"—"}</b><small>İZLENEN MODEL</small></div></section>
    {error&&<div className="error">API bağlantısı kurulamadı. Backend servisinin çalıştığını kontrol et.</div>}
    <section className="metric-grid">{[["İzlenen model",stats.models],["Takip edilen firma",stats.companies],["Fiyat gözlemi",stats.price_observations],["Tespit edilen olay",stats.change_events]].map(([label,value])=><article className="metric" key={String(label)}><p>{label}</p><strong>{loading?"—":compact(Number(value))}</strong><span>● Güncel veri</span></article>)}</section>

    <section className="official-section" id="leaderboard">
      {(()=>{const boards={general:arena,coding:swebench,"swe-live":swebenchLive,"tau-bench":tauBench,intelligence:aaIntelligence,"aa-coding":aaCoding,agentic:aaAgentic,livebench,"mmlu-pro":mmluPro,livecodebench};const board=boards[leaderboardView];const isArena=leaderboardView==="general";const isSwe=leaderboardView==="coding";const isSweLive=leaderboardView==="swe-live";const isTau=leaderboardView==="tau-bench";const isLive=leaderboardView==="livebench";const isMmlu=leaderboardView==="mmlu-pro";const isLiveCode=leaderboardView==="livecodebench";return <><div className="section-title"><div><p className="kicker">DOĞRUDAN KAYNAK VERİSİ</p><h2>{isArena?"Genel / İnsan tercihi":isSwe?"Kodlama / Agent":isSweLive?"SWE-bench Live":isTau?"τ-bench Araç Kullanımı":isLive?"LiveBench Genel":isMmlu?"MMLU-Pro Bilgi":isLiveCode?"LiveCodeBench Kod Üretimi":leaderboardView==="intelligence"?"Zekâ Endeksi":leaderboardView==="aa-coding"?"Kodlama Endeksi":"Agentic Endeksi"}</h2></div><p>{board?.published_at?`Kaynak snapshot tarihi: ${new Date(board.published_at).toLocaleDateString("tr-TR")}`:"Veri kaynağı yapılandırılıyor"}</p></div>
      <div className="leaderboard-tabs"><button className={isArena?"active":""} onClick={()=>setLeaderboardView("general")}>Genel — Arena</button><button className={isSwe?"active":""} onClick={()=>setLeaderboardView("coding")}>Kodlama — SWE-bench</button><button disabled={!swebenchLive} className={isSweLive?"active":""} onClick={()=>setLeaderboardView("swe-live")}>SWE-bench Live</button><button disabled={!tauBench} className={isTau?"active":""} onClick={()=>setLeaderboardView("tau-bench")}>τ-bench</button><button disabled={!livecodebench} className={isLiveCode?"active":""} onClick={()=>setLeaderboardView("livecodebench")}>LiveCodeBench</button><button disabled={!aaIntelligence} className={leaderboardView==="intelligence"?"active":""} onClick={()=>setLeaderboardView("intelligence")}>Zekâ — AA</button><button disabled={!aaCoding} className={leaderboardView==="aa-coding"?"active":""} onClick={()=>setLeaderboardView("aa-coding")}>Kodlama — AA</button><button disabled={!aaAgentic} className={leaderboardView==="agentic"?"active":""} onClick={()=>setLeaderboardView("agentic")}>Agentic — AA</button><button disabled={!livebench} className={isLive?"active":""} onClick={()=>setLeaderboardView("livebench")}>LiveBench</button><button disabled={!mmluPro} className={isMmlu?"active":""} onClick={()=>setLeaderboardView("mmlu-pro")}>MMLU-Pro</button></div>
      {isLive&&<div className="benchmark-category"><label htmlFor="livebench-category">LiveBench kategorisi</label><select id="livebench-category" value={livebenchCategory} onChange={e=>setLivebenchCategory(e.target.value)}><option value="overall">Genel</option><option value="reasoning">Reasoning</option><option value="math">Matematik</option><option value="coding">Kodlama</option><option value="data_analysis">Veri analizi</option><option value="writing">Yazma</option><option value="instruction_following">Talimat takibi</option><option value="agentic_coding">Agentic kodlama</option></select></div>}
      {isMmlu&&<div className="benchmark-category"><label htmlFor="mmlu-category">MMLU-Pro alanı</label><select id="mmlu-category" value={mmluCategory} onChange={e=>setMmluCategory(e.target.value)}><option value="overall">Genel</option>{[["biology","Biyoloji"],["business","İşletme"],["chemistry","Kimya"],["computer_science","Bilgisayar bilimi"],["economics","Ekonomi"],["engineering","Mühendislik"],["health","Sağlık"],["history","Tarih"],["law","Hukuk"],["math","Matematik"],["philosophy","Felsefe"],["physics","Fizik"],["psychology","Psikoloji"],["other","Diğer"]].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div>}
      {isSweLive&&<div className="benchmark-category"><label htmlFor="swe-live-category">SWE-bench Live bölümü</label><select id="swe-live-category" value={sweLiveCategory} onChange={e=>setSweLiveCategory(e.target.value)}>{[["lite","Lite"],["full","Full"],["verified","Verified"],["ccpp","C / C++"],["csharp","C#"],["go","Go"],["java","Java"],["rust","Rust"],["tsjs","TypeScript / JavaScript"],["windows","Windows"]].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div>}
      {isTau&&<div className="benchmark-category"><label htmlFor="tau-category">τ-bench alanı</label><select id="tau-category" value={tauCategory} onChange={e=>setTauCategory(e.target.value)}>{[["airline","Havayolu"],["retail","Perakende"],["telecom","Telekom"],["banking_knowledge","Bankacılık bilgisi"]].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div>}
      <div className="official-source"><span>{isArena?"İnsan tercihleriyle ölçülen Text Arena / Overall":isSwe?"Gerçek GitHub sorunlarında çözülen görev oranı / SWE-bench Verified":isSweLive?"Güncel, çok dilli gerçek yazılım görevlerinde çözülen sorun oranı":isTau?"Gerçekçi araç kullanımı görevlerinde kaynağın doğrudan Pass@1 sonucu":isLive?"Güncellenen, kontaminasyon azaltılmış akademik değerlendirme":isMmlu?"14 alanda zorlaştırılmış akademik bilgi ve akıl yürütme ölçümü":isLiveCode?"Resmî tarih penceresi ve kontaminasyon filtresiyle Pass@1 kod üretimi":"Artificial Analysis bağımsız ölçümü"}</span>{board&&<a href={board.source.url} target="_blank" rel="noreferrer">Resmî kaynağı aç ↗</a>}</div>
      {isArena&&<p className="arena-note">Genel Arena sıralaması temel olarak <strong>Arena Rating</strong> puanına göre yapılır; oy sayısı ve güven aralığı bağlam bilgisidir.</p>}
      <div className="panel table-wrap official-table"><table><thead><tr><th>SIRA</th><th>MODEL</th><th>KURULUŞ</th><th>{isArena?"ARENA RATING":isSwe||isSweLive?"ÇÖZÜM ORANI":isTau?"PASS@1":"KAYNAK PUANI"}</th><th>{isArena?"OY":isSwe||isSweLive?"DEĞERLENDİRME":isTau?"BENCHMARK":isLive?"SÜRÜM":isMmlu?"VERİ KAYNAĞI":"SÜRÜM"}</th><th>{isArena?"GÜVEN ARALIĞI":isSwe||isSweLive?"AGENT / HARNESS":isTau?"YAYIN TARİHİ":"GÜNCELLİK"}</th></tr></thead><tbody>{board?.items.map(item=><tr key={`${item.rank}-${item.model_name}`}><td><strong className="official-rank">#{item.rank}</strong></td><td><strong>{item.model_name}</strong><small>{item.license}</small></td><td><span className="company-chip">{item.organization}</span></td><td><strong className="official-rating">{isArena?Math.round(item.rating):isSwe||isSweLive||isTau?`${item.rating.toFixed(2)}%`:item.rating.toFixed(1)}</strong></td><td className="mono">{isArena?(item.vote_count?.toLocaleString("tr-TR")??"—"):isSwe?String(item.details.evaluation_date??"—"):isSweLive?String(item.details.submission_date??"—"):isTau?String(item.details.benchmark_version??"—"):isLive?String(item.details.release??"—"):isMmlu?String(item.details.evaluation_source??"—"):String(item.details.benchmark_version??"—")}</td><td className="mono">{isArena&&item.rating_lower!=null&&item.rating_upper!=null?`${Math.round(item.rating_lower)}–${Math.round(item.rating_upper)}`:isSwe?String(item.details.agent??"—"):isSweLive?String(item.details.agent_harness??"—"):item.leaderboard_publish_date}</td></tr>)}</tbody></table></div></>})()}
    </section>

    <section className="catalog-section" id="models">
      <button className="catalog-toggle" type="button" aria-expanded={catalogOpen} aria-controls="model-catalog-content" onClick={()=>setCatalogOpen(open=>!open)}><div className="section-title"><div><p className="kicker">MODEL KATALOĞU</p><h2>{loading?"Modeller yükleniyor…":`${stats.models} model, tek radar.`}</h2></div><div className="catalog-toggle-action"><span>{catalogOpen?"Tabloyu kapat":"Modelleri göster"}</span><b>{catalogOpen?"−":"+"}</b></div></div></button>
      {catalogOpen&&<div id="model-catalog-content"><p className="catalog-price-note">Fiyatlar USD / 1 milyon token cinsindedir.</p>
      <div className="filters"><label className="search"><span>⌕</span><input value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="Model, firma veya sağlayıcı ara"/></label><select value={company} onChange={e=>{setCompany(e.target.value);setPage(1)}} aria-label="Firma filtresi"><option value="all">Tüm firmalar ({companies.length})</option>{companies.map(c=><option key={c.slug} value={c.slug}>{c.name}</option>)}</select><span className="result-count">{filtered.length} sonuç</span></div>
      <div className="panel table-wrap rich-table"><table><thead><tr><th>SEÇ</th><th>MODEL</th><th>FİRMA</th><th>CONTEXT</th><th>GİRDİ</th><th>ÇIKTI</th><th>MODALİTE</th><th></th></tr></thead><tbody>{visible.map(model=><tr key={model.id}><td><button className={`select-btn ${selected.some(m=>m.id===model.id)?"selected":""}`} onClick={()=>toggle(model)} aria-label={`${model.name} karşılaştırmaya ekle`}>{selected.some(m=>m.id===model.id)?"✓":"+"}</button></td><td><strong>{model.name}</strong><small>{model.slug}</small></td><td><span className="company-chip">{model.company.name}</span></td><td className="mono">{model.context_window?.toLocaleString("tr-TR")??"—"}</td><td className="price">{money(model.pricing?.input)}</td><td className="price">{money(model.pricing?.output)}</td><td>{model.capabilities.input_modalities?.join(" + ")||"—"}</td><td><button className="detail-btn" onClick={()=>openDetail(model)}>İncele →</button></td></tr>)}</tbody></table></div>
      <div className="pagination"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>← Önceki</button><span>Sayfa {page} / {pages}</span><button disabled={page===pages} onClick={()=>setPage(p=>p+1)}>Sonraki →</button></div></div>}
    </section>

    <section className="compare-section" id="compare"><div className="section-title"><div><p className="kicker">MODEL KARŞILAŞTIRMA</p><h2>Yan yana karar ver.</h2></div><p>Tablodaki + düğmesiyle en fazla 3 model seç.</p></div>{selected.length===0?<div className="empty-state">Karşılaştırmak istediğin modelleri katalogdan seç.</div>:<div className="compare-grid">{selected.map(model=><article key={model.id}><button className="remove" onClick={()=>toggle(model)}>×</button><p>{model.company.name}</p><h3>{model.name}</h3><dl><div><dt>Context</dt><dd>{model.context_window?.toLocaleString("tr-TR")??"—"}</dd></div><div><dt>Girdi / 1M</dt><dd>{money(model.pricing?.input)}</dd></div><div><dt>Çıktı / 1M</dt><dd>{money(model.pricing?.output)}</dd></div><div><dt>Girdi türü</dt><dd>{model.capabilities.input_modalities?.join(", ")||"—"}</dd></div><div><dt>Çıktı türü</dt><dd>{model.capabilities.output_modalities?.join(", ")||"—"}</dd></div></dl><button className="wide-btn" onClick={()=>openDetail(model)}>Tüm ayrıntılar</button></article>)}</div>}</section>

    <section className="events-section" id="events"><div className="section-title"><div><p className="kicker">TEKNOLOJİ AKIŞI</p><h2>Radar’a yeni düşenler.</h2></div><p>Yeni modeller, benchmark hareketleri, yetenekler, context ve fiyat değişimleri; doğrulanmış kaynaklardan dengeli bir akış.</p></div><div className="event-legend"><span><i className="release"/>Yeni model</span><span><i className="benchmark"/>Benchmark</span><span><i className="technology"/>Teknoloji</span><span><i className="price"/>Fiyat</span></div><div className="event-grid">{visibleEvents.map(event=>{const meta=eventInfo(event.event_type);return <article className={`event-card ${meta.className}`} key={event.id}><div className="event-card-head"><span className="event-icon">{meta.icon}</span><p>{meta.label}</p></div><strong>{cleanEventTitle(event)}</strong><small>{eventDetail(event)}</small><time>{new Date(event.detected_at).toLocaleString("tr-TR")}</time></article>})}</div></section>
    <section className="catalog-section" id="research"><div className="section-title"><div><p className="kicker">ARAŞTIRMA VE BİLDİRİM</p><h2>Makaleler, uyarılar, kanıt.</h2></div><p>arXiv ve laboratuvar duyuruları kaynak URL’siyle; bildirimler önem seviyesine göre.</p></div><div className="intel-grid">{research.length?research.map(paper=><article key={paper.id}><p>ARAŞTIRMA</p><h3>{paper.title}</h3><small>{(paper.authors||[]).slice(0,3).join(", ")||"Yazar yok"}</small>{canOpenSourceUrl(paper.url)&&<a href={paper.url} target="_blank" rel="noreferrer">Kaynağı aç ↗</a>}</article>):<article className="empty-card"><p>ARAŞTIRMA</p><h3>Henüz makale toplanmadı</h3><small>Scheduler arXiv collector’ını çalıştırınca burada görünür.</small></article>}{notices.map(notice=><article key={notice.id} className={`notice ${notice.importance}`}><p>{notice.importance}</p><h3>{notice.title}</h3><small>{notice.body}</small>{canOpenSourceUrl(notice.source_url)&&<a href={notice.source_url??""} target="_blank" rel="noreferrer">Kaynağı aç ↗</a>}<time>{new Date(notice.created_at).toLocaleString("tr-TR")}</time></article>)}</div></section>
    <section className="compare-section" id="radar"><div className="section-title"><div><p className="kicker">TEKNOLOJİ RADARI</p><h2>Agent, MCP, computer use.</h2></div><p>GitHub sürümleri ve araştırma metinlerinden çıkan sinyaller; uydurulmaz, yalnızca görülen kanıt kaydedilir.</p></div>{technology.length?<div className="compare-grid">{technology.map(signal=><article key={signal.slug}><p>{signal.category}</p><h3>{signal.name}</h3><dl><div><dt>Güç</dt><dd>{signal.strength}</dd></div><div><dt>Son görülme</dt><dd>{new Date(signal.last_seen_at).toLocaleDateString("tr-TR")}</dd></div></dl></article>)}</div>:<div className="empty-state">Teknoloji sinyali henüz yok. GitHub ve arXiv collector’ları dolduracak.</div>}</section>
    <section className="catalog-section" id="sources"><div className="section-title"><div><p className="kicker">KAYNAK KATALOĞU</p><h2>Kim söyledi, nerede, ne zaman.</h2></div><p>Resmî, bağımsız ve akademik kaynaklar; sınıf, yöntem ve son başarılı kontrol ile.</p></div><div className="panel table-wrap rich-table"><table><thead><tr><th>KAYNAK</th><th>SINIF</th><th>YÖNTEM</th><th>GÜVEN</th><th>DURUM</th></tr></thead><tbody>{sourceCatalog.map(source=><tr key={source.slug}><td><strong>{source.name}</strong><small><a href={source.url} target="_blank" rel="noreferrer">{source.url}</a></small></td><td>{source.source_class}</td><td>{source.collection_method}</td><td>{source.reliability}</td><td>{source.status??(source.is_active?"aktif":"pasif")}</td></tr>)}</tbody></table></div></section>
    <footer><span>LLM RADAR / 2026</span><span>OpenRouter kaynaklı • Yakın gerçek zamanlı takip</span></footer>

    {(detailLoading||detail)&&<div className="modal-backdrop" role="button" tabIndex={0} aria-label="Model ayrıntılarını kapat" onClick={e=>{if(e.target===e.currentTarget)setDetail(null)}} onKeyDown={e=>{if(e.key==="Escape"||e.key==="Enter"||e.key===" ")setDetail(null)}}><aside className="detail-drawer">{detailLoading?<div className="drawer-loading">Model ayrıntıları yükleniyor…</div>:detail&&<><button className="drawer-close" onClick={()=>setDetail(null)}>×</button><p className="kicker">{detail.company.name}</p><h2>{detail.name}</h2><code>{detail.slug}</code><p className="description">{detail.description||"Bu model için açıklama bulunmuyor."}</p><div className="detail-stats"><div><span>Bağlam</span><strong>{detail.context_window?.toLocaleString("tr-TR")??"—"}</strong></div><div><span>Tokenlaştırıcı</span><strong>{detail.tokenizer||"—"}</strong></div><div><span>Girdi fiyatı</span><strong>{money(detail.price_history[0]?.input)}</strong></div><div><span>Çıktı fiyatı</span><strong>{money(detail.price_history[0]?.output)}</strong></div></div><h3>Benchmark karnesi</h3>{detail.benchmarks.length?<div className="benchmark-list">{detail.benchmarks.map(score=><a key={score.benchmark_slug} href={score.source_url} target="_blank" rel="noreferrer"><span>{score.benchmark}</span><strong>#{score.rank} · {score.score.toFixed(1)}</strong></a>)}</div>:<p className="description">Bu model adıyla eşleşen resmî benchmark sonucu henüz yok.</p>}<h3>Yetenekler</h3><div className="tags">{[...(detail.capabilities.input_modalities||[]),...(detail.capabilities.output_modalities||[])].map((tag,i)=><span key={`${tag}-${i}`}>{trModality(tag)}</span>)}</div>{(()=>{const srcs=detail.sources&&detail.sources.length>0?detail.sources:[{name:"OpenRouter",url:`https://openrouter.ai/${detail.slug}`,reliability:"third_party",source_class:"independent"}];return srcs.map((src,i)=>{const rawUrl=src.url??"";const isOpenRouterSource=src.name.toLowerCase().includes("openrouter")||rawUrl.includes("openrouter.ai/api/v1/models");const href=isOpenRouterSource?`https://openrouter.ai/${detail.slug}`:rawUrl;const canOpen=canOpenSourceUrl(href);const label=src.reliability==="official_api"?"Resmî API verisi":src.reliability==="official_document"?"Resmî dokümantasyon":src.reliability==="independent_measurement"?"Bağımsız ölçüm":src.reliability==="academic"?"Akademik kaynak":src.reliability==="third_party"?"Üçüncü taraf sağlayıcı verisi":"Topluluk verisi";return <div className="source-card" key={i}><span>KAYNAK VE GÜVENİLİRLİK</span><strong>{src.name==="openrouter"?"OpenRouter":src.name}</strong><p>{label}</p>{canOpen?<a href={href} target="_blank" rel="noreferrer">Kaynağı aç ↗</a>:<small className="source-link-disabled">Görüntülenebilir kaynak sayfası yok</small>}</div>})})()}</>}</aside></div>}
  </main>
}
