"""create core tables

Revision ID: 2b8cf77e50f1
Revises:
Create Date: 2026-08-12 19:20:45.906692
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2b8cf77e50f1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('reliability_level', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('change_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('change_percentage', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('importance', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_events_detected_at'), 'change_events', ['detected_at'], unique=False)
    op.create_index(op.f('ix_change_events_entity_id'), 'change_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_change_events_event_type'), 'change_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_change_events_source_id'), 'change_events', ['source_id'], unique=False)
    op.create_table('models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('family', sa.String(length=120), nullable=True),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('is_open_weight', sa.Boolean(), nullable=True),
    sa.Column('license', sa.String(length=120), nullable=True),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_company_id'), 'models', ['company_id'], unique=False)
    op.create_index(op.f('ix_models_slug'), 'models', ['slug'], unique=True)
    op.create_table('model_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_snapshots_content_hash'), 'model_snapshots', ['content_hash'], unique=False)
    op.create_index(op.f('ix_model_snapshots_model_id'), 'model_snapshots', ['model_id'], unique=False)
    op.create_index(op.f('ix_model_snapshots_observed_at'), 'model_snapshots', ['observed_at'], unique=False)
    op.create_index(op.f('ix_model_snapshots_source_id'), 'model_snapshots', ['source_id'], unique=False)
    op.create_table('price_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=False),
    sa.Column('input_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('output_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('cache_read_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('cache_write_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_observations_model_id'), 'price_observations', ['model_id'], unique=False)
    op.create_index(op.f('ix_price_observations_observed_at'), 'price_observations', ['observed_at'], unique=False)
    op.create_index(op.f('ix_price_observations_source_id'), 'price_observations', ['source_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_observations_source_id'), table_name='price_observations')
    op.drop_index(op.f('ix_price_observations_observed_at'), table_name='price_observations')
    op.drop_index(op.f('ix_price_observations_model_id'), table_name='price_observations')
    op.drop_table('price_observations')
    op.drop_index(op.f('ix_model_snapshots_source_id'), table_name='model_snapshots')
    op.drop_index(op.f('ix_model_snapshots_observed_at'), table_name='model_snapshots')
    op.drop_index(op.f('ix_model_snapshots_model_id'), table_name='model_snapshots')
    op.drop_index(op.f('ix_model_snapshots_content_hash'), table_name='model_snapshots')
    op.drop_table('model_snapshots')
    op.drop_index(op.f('ix_models_slug'), table_name='models')
    op.drop_index(op.f('ix_models_company_id'), table_name='models')
    op.drop_table('models')
    op.drop_index(op.f('ix_change_events_source_id'), table_name='change_events')
    op.drop_index(op.f('ix_change_events_event_type'), table_name='change_events')
    op.drop_index(op.f('ix_change_events_entity_id'), table_name='change_events')
    op.drop_index(op.f('ix_change_events_detected_at'), table_name='change_events')
    op.drop_table('change_events')
    op.drop_table('sources')
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
