"""add processed events

Revision ID: 50c35a26d251
Revises: 2b8cf77e50f1
Create Date: 2026-08-12 19:24:09.305792
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '50c35a26d251'
down_revision: Union[str, None] = '2b8cf77e50f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=160), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_processed_events_source'), 'processed_events', ['source'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processed_events_source'), table_name='processed_events')
    op.drop_table('processed_events')
    # ### end Alembic commands ###
